### ISSUE TITLE
How to define commands longer than a word?.

### ISSUE THREAD

**Issue by eko234** [merlinfo/merlin#3]
Hello, I'm trying out merlin, pretty interesting btw, I want to know if I can use more complex system commands like like lest say:
```forth
i_contain_something 'grep "something"' ;infuse
```

**Comment by geremachek** [comment]
> Hello, I'm trying out merlin, pretty interesting btw, I want to know if I can use more complex system commands like like lest say:
> 
> ```forth
> 
> i_contain_something 'grep "something"' ;infuse
> 
> ```

You need to enter scribe mode to create atoms containing spaces.

```
;scribe
some text.
;atom
```

Will push "some text." To the stack. `;scribe` switches the input mode from evaluating every whitespace separated element separately in a line of input to evaluating each line as a whole. `;atom` switches it back.

Hope this helps.

**Comment by eko234** [comment]
Thanks master, for I have been enlightened :pray:

**Comment by geremachek** [comment]
🙏
